[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-Wl,-rpath,/nix/store/57iz36553175g3178pvxjij8z5rcsd4n-glibc-2.42-61/lib",
    "-C", "link-arg=-Wl,-dynamic-linker,/nix/store/57iz36553175g3178pvxjij8z5rcsd4n-glibc-2.42-61/lib/ld-linux-x86-64.so.2",
]