use utoipa::openapi::security::{ApiKey, ApiKeyValue, SecurityScheme};
use utoipa::{Modify, OpenApi};

struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "cookieAuth",
                SecurityScheme::ApiKey(ApiKey::Cookie(ApiKeyValue::new("session_id"))),
            );
        }
    }
}

#[derive(OpenApi)]
#[openapi(
    info(
        title = "VexBoard API",
        version = env!("CARGO_PKG_VERSION"),
        description = "Self-hosted server dashboard REST API",
        license(name = "MIT"),
        contact(name = "VexBoard", email = "victorytech@proton.me"),
    ),
    paths(
        crate::api::health::health_check,
        crate::api::setup::status,
        crate::api::setup::create_admin,
        crate::api::auth::login,
        crate::api::auth::logout,
        crate::api::auth::me,
        crate::api::auth::update_me,
        crate::api::auth::update_sort_mode,
        crate::api::services::list_services,
        crate::api::services::stream_service_events,
        crate::api::services::service_history,
        crate::api::services::service_uptime_summary,
        crate::api::services::create_service,
        crate::api::services::update_service,
        crate::api::services::delete_service,
        crate::api::services::claim_service,
        crate::api::services::start_service,
        crate::api::services::stop_service,
        crate::api::services::restart_service,
        crate::api::services::service_logs_stream,
        crate::api::services::reorder_services,
        crate::api::groups::list_groups,
        crate::api::groups::create_group,
        crate::api::groups::update_group,
        crate::api::groups::delete_group,
        crate::api::quick_links::list_quick_links,
        crate::api::quick_links::create_quick_link,
        crate::api::quick_links::update_quick_link,
        crate::api::quick_links::delete_quick_link,
        crate::api::quick_links::reorder_quick_links,
        crate::api::audit::list_audit,
        crate::api::users::list_users,
        crate::api::users::create_user,
        crate::api::users::update_user,
        crate::api::users::delete_user,
        crate::api::settings::get_auth_mode,
        crate::api::settings::set_auth_mode,
        crate::api::notifications::list_channels,
        crate::api::notifications::create_channel,
        crate::api::notifications::update_channel,
        crate::api::notifications::delete_channel,
        crate::api::notifications::test_channel,
        crate::api::config_export::export_config,
        crate::api::config_export::import_config,
        crate::api::config_export::export_nix,
        crate::api::metrics::metrics_snapshot,
        crate::api::metrics::metrics_stream,
        crate::discovery::list_discovered,
        crate::discovery::trigger_refresh,
        crate::discovery::dismiss_unit,
        crate::discovery::undismiss_unit,
    ),
    components(
        schemas(
            crate::db::models::Group,
            crate::db::models::Service,
            crate::db::models::CreateService,
            crate::db::models::UpdateService,
            crate::db::models::CreateGroup,
            crate::db::models::UpdateGroup,
            crate::db::models::LoginRequest,
            crate::db::models::UserInfo,
            crate::api::auth::UpdateSortModeRequest,
            crate::db::models::ServiceWithStatus,
            crate::db::models::ProbeHistoryPoint,
            crate::db::models::Incident,
            crate::db::models::UptimeSummary,
            crate::db::models::QuickLink,
            crate::db::models::CreateQuickLink,
            crate::db::models::UpdateQuickLink,
            crate::db::models::ReorderItem,
            crate::db::models::AuditEvent,
            crate::db::models::UserPublic,
            crate::db::models::CreateUserRequest,
            crate::db::models::UpdateUserRequest,
            crate::api::settings::AuthModeStatus,
            crate::api::settings::SetAuthModeRequest,
            crate::db::models::NotificationChannel,
            crate::db::models::CreateNotificationChannel,
            crate::db::models::UpdateNotificationChannel,
            crate::db::models::ConfigExport,
            crate::db::models::ExportedGroup,
            crate::db::models::ExportedService,
            crate::db::models::ExportedQuickLink,
            crate::db::models::ExportedNotificationChannel,
            crate::db::models::ExportedSettings,
            crate::db::models::ConfigImportSummary,
            crate::api::setup::SetupRequest,
            crate::discovery::DiscoveredUnit,
            crate::discovery::DismissRequest,
        )
    ),
    modifiers(&SecurityAddon),
    tags(
        (name = "health", description = "Health check"),
        (name = "setup", description = "Initial admin setup (one-time bootstrap)"),
        (name = "auth", description = "Authentication (login, logout, profile)"),
        (name = "services", description = "Service management"),
        (name = "groups", description = "Group management"),
        (name = "quick-links", description = "Quick link management"),
        (name = "audit", description = "Audit log — requires authentication"),
        (name = "metrics", description = "System metrics (REST snapshot + SSE stream)"),
        (name = "discovery", description = "Auto-discovery of systemd units and containers"),
        (name = "users", description = "User management — admin only"),
        (name = "settings", description = "Runtime settings — admin only"),
    )
)]
pub struct ApiDoc;
